// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/manga.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manga struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Genres        []string               `protobuf:"bytes,4,rep,name=genres,proto3" json:"genres,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TotalChapters int32                  `protobuf:"varint,6,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manga) Reset() {
	*x = Manga{}
	mi := &file_proto_manga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manga) ProtoMessage() {}

func (x *Manga) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manga.ProtoReflect.Descriptor instead.
func (*Manga) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{0}
}

func (x *Manga) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manga) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Manga) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manga) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Manga) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Manga) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *Manga) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMangaRequest) Reset() {
	*x = GetMangaRequest{}
	mi := &file_proto_manga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaRequest) ProtoMessage() {}

func (x *GetMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaRequest.ProtoReflect.Descriptor instead.
func (*GetMangaRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{1}
}

func (x *GetMangaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         *Manga                 `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaResponse) Reset() {
	*x = MangaResponse{}
	mi := &file_proto_manga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaResponse) ProtoMessage() {}

func (x *MangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaResponse.ProtoReflect.Descriptor instead.
func (*MangaResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{2}
}

func (x *MangaResponse) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_manga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Manga               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_manga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetResults() []*Manga {
	if x != nil {
		return x.Results
	}
	return nil
}

type ProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MangaId       string                 `protobuf:"bytes,2,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	Chapter       int32                  `protobuf:"varint,3,opt,name=chapter,proto3" json:"chapter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressRequest) Reset() {
	*x = ProgressRequest{}
	mi := &file_proto_manga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressRequest) ProtoMessage() {}

func (x *ProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressRequest.ProtoReflect.Descriptor instead.
func (*ProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{5}
}

func (x *ProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProgressRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *ProgressRequest) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

type ProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_proto_manga_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{6}
}

func (x *ProgressResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_manga_proto protoreflect.FileDescriptor

const file_proto_manga_proto_rawDesc = "" +
	"\n" +
	"\x11proto/manga.proto\x12\bmangahub\"\xbe\x01\n" +
	"\x05Manga\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x16\n" +
	"\x06genres\x18\x04 \x03(\tR\x06genres\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0etotal_chapters\x18\x06 \x01(\x05R\rtotalChapters\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"!\n" +
	"\x0fGetMangaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\rMangaResponse\x12%\n" +
	"\x05manga\x18\x01 \x01(\v2\x0f.mangahub.MangaR\x05manga\";\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\";\n" +
	"\x0eSearchResponse\x12)\n" +
	"\aresults\x18\x01 \x03(\v2\x0f.mangahub.MangaR\aresults\"_\n" +
	"\x0fProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bmanga_id\x18\x02 \x01(\tR\amangaId\x12\x18\n" +
	"\achapter\x18\x03 \x01(\x05R\achapter\"\"\n" +
	"\x10ProgressResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xd9\x01\n" +
	"\fMangaService\x12>\n" +
	"\bGetManga\x12\x19.mangahub.GetMangaRequest\x1a\x17.mangahub.MangaResponse\x12@\n" +
	"\vSearchManga\x12\x17.mangahub.SearchRequest\x1a\x18.mangahub.SearchResponse\x12G\n" +
	"\x0eUpdateProgress\x12\x19.mangahub.ProgressRequest\x1a\x1a.mangahub.ProgressResponseB\x16Z\x14mangahub/proto;protob\x06proto3"

var (
	file_proto_manga_proto_rawDescOnce sync.Once
	file_proto_manga_proto_rawDescData []byte
)

func file_proto_manga_proto_rawDescGZIP() []byte {
	file_proto_manga_proto_rawDescOnce.Do(func() {
		file_proto_manga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_manga_proto_rawDesc), len(file_proto_manga_proto_rawDesc)))
	})
	return file_proto_manga_proto_rawDescData
}

var file_proto_manga_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_manga_proto_goTypes = []any{
	(*Manga)(nil),            // 0: mangahub.Manga
	(*GetMangaRequest)(nil),  // 1: mangahub.GetMangaRequest
	(*MangaResponse)(nil),    // 2: mangahub.MangaResponse
	(*SearchRequest)(nil),    // 3: mangahub.SearchRequest
	(*SearchResponse)(nil),   // 4: mangahub.SearchResponse
	(*ProgressRequest)(nil),  // 5: mangahub.ProgressRequest
	(*ProgressResponse)(nil), // 6: mangahub.ProgressResponse
}
var file_proto_manga_proto_depIdxs = []int32{
	0, // 0: mangahub.MangaResponse.manga:type_name -> mangahub.Manga
	0, // 1: mangahub.SearchResponse.results:type_name -> mangahub.Manga
	1, // 2: mangahub.MangaService.GetManga:input_type -> mangahub.GetMangaRequest
	3, // 3: mangahub.MangaService.SearchManga:input_type -> mangahub.SearchRequest
	5, // 4: mangahub.MangaService.UpdateProgress:input_type -> mangahub.ProgressRequest
	2, // 5: mangahub.MangaService.GetManga:output_type -> mangahub.MangaResponse
	4, // 6: mangahub.MangaService.SearchManga:output_type -> mangahub.SearchResponse
	6, // 7: mangahub.MangaService.UpdateProgress:output_type -> mangahub.ProgressResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_manga_proto_init() }
func file_proto_manga_proto_init() {
	if File_proto_manga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_manga_proto_rawDesc), len(file_proto_manga_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_manga_proto_goTypes,
		DependencyIndexes: file_proto_manga_proto_depIdxs,
		MessageInfos:      file_proto_manga_proto_msgTypes,
	}.Build()
	File_proto_manga_proto = out.File
	file_proto_manga_proto_goTypes = nil
	file_proto_manga_proto_depIdxs = nil
}
